subscription_id = "552d3bbc-1a07-49fa-9df2-d755c784c4e7"
location        = "uksouth"
environment     = "dev"
project_name    = "event-platform"

resource_group_name        = "event-platform-rg"
storage_account_name       = "eventplatformstoragesdd"
servicebus_namespace_name  = "event-platform-sb-scott"
servicebus_queue_name      = "event-queue-dev"
application_insights_name  = "event-platform-ai"
key_vault_name             = "event-platform-kv"
api_service_plan_name      = "ASP-eventplatformrg-a2f8"
function_service_plan_name = "ASP-eventplatformrg-9edf"
api_app_name               = "event-platform-api-scott-dev"
function_app_name          = "event-platform-func-scott-dev"
blob_container_name        = "events-dev"
