subscription_id = "552d3bbc-1a07-49fa-9df2-d755c784c4e7"
location        = "uksouth"
environment     = "prod"
project_name    = "event-platform"

resource_group_name        = "event-platform-prod-rg"
storage_account_name       = "eventplatformprodsdd"
servicebus_namespace_name  = "event-platform-sb-scott-prod"
servicebus_queue_name      = "event-queue-prod"
application_insights_name  = "event-platform-ai-prod"
key_vault_name             = "event-platform-kv-prod"
api_service_plan_name      = "asp-event-platform-api-prod"
function_service_plan_name = "asp-event-platform-func-prod"
api_app_name               = "event-platform-api-scott-prod"
function_app_name          = "event-platform-func-scott-prod"
blob_container_name        = "events-prod"
