name: Terraform CI

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

  push:
    branches:
      - develop
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Format Validate Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.1

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan without refresh
        run: terraform plan -refresh=false